### ISSUE TITLE
Cloudflare Human Verification Still Required Despite Code Execution

### ISSUE THREAD

**Issue by KevinLvLight** [ganarkf/solana-wallet-checker#1]
Hello,

I executed the code you provided, but I am still encountering Cloudflare’s human verification (captcha) when trying to access the site. Could you clarify why this might be happening?

Is there any additional configuration or step I might have missed that could help bypass this verification?

Thank you for your assistance!

**Comment by ganarkf** [comment]
For now, I manually verify the captcha, and I have never tried to code that
bypass the cloudflare captcha. Maybe you can search the code to bypass the
captcha yourself.

**Comment by KevinLvLight** [comment]
All right, thanks.
